-- MySQL Script generated by MySQL Workbench
-- Ter 03 Out 2017 19:38:55 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mundo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mundo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mundo` DEFAULT CHARACTER SET utf8 ;
USE `mundo` ;

-- -----------------------------------------------------
-- Table `mundo`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundo`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `nomePais` VARCHAR(45) NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundo`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundo`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nomeEstado` VARCHAR(45) NULL,
  `Pais_idPais` INT NOT NULL,
  PRIMARY KEY (`idEstado`),
  INDEX `fk_Estado_Pais_idx` (`Pais_idPais` ASC),
  CONSTRAINT `fk_Estado_Pais`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `mundo`.`Pais` (`idPais`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundo`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundo`.`Cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nomeCidade` VARCHAR(45) NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fk_Cidade_Estado1_idx` (`Estado_idEstado` ASC),
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mundo`.`Estado` (`idEstado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
